# Basic matrix operations with numpy

In [1]:
import numpy as np

In [3]:
matrix_a = np.array([[1, 3, 5],
                     [2, -4, 6],
                     [5, -1, 2]])

In [4]:
matrix_b = np.array([[2, -2, 3],
                     [4, 0, 5],
                     [0, -1, 7]])

## Addition and subtraction

In [5]:
matrix_a + matrix_b

array([[ 3,  1,  8],
       [ 6, -4, 11],
       [ 5, -2,  9]])

## Multiplication

In [7]:
matrix_a@matrix_b

array([[ 14,  -7,  53],
       [-12, -10,  28],
       [  6, -12,  24]])

In [9]:
matrix_b@matrix_a

array([[13, 11,  4],
       [29,  7, 30],
       [33, -3,  8]])

## Inverting a matrix

In [10]:
np.linalg.inv(matrix_a)

array([[-0.01204819, -0.06626506,  0.22891566],
       [ 0.15662651, -0.13855422,  0.02409639],
       [ 0.10843373,  0.09638554, -0.06024096]])

## Finding the rank of a matrix

In [15]:
np.linalg.matrix_rank(matrix_a)

3

## Calculating the determinant

In [16]:
np.linalg.det(matrix_a)

166.00000000000006

## Getting the diagonal of a matrix

In [17]:
matrix_a.diagonal()

array([ 1, -4,  2])

## Finding eigenvalues and eigenvectors

In [23]:
matrix_c = np.array([[1, 0, 5],
                     [0, 2, 6],
                     [0, 0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(matrix_c)

In [24]:
eigenvalues

array([1., 2., 3.])

In [25]:
eigenvectors

array([[1.        , 0.        , 0.38014296],
       [0.        , 1.        , 0.91234311],
       [0.        , 0.        , 0.15205718]])

## Transposing a matrix

In [26]:
matrix_d = np.array([[1, 0],
                     [0, 2],
                     [0, 0]])

In [27]:
matrix_d.T

array([[1, 0, 0],
       [0, 2, 0]])

## Selecting element

In [28]:
# Select row 1 and row 2 of a metrix
matrix_d[:2, :]

array([[1, 0],
       [0, 2]])

In [29]:
# Select the first column of a matrix
matrix_d[:, :1]

array([[1],
       [0],
       [0]])